### ISSUE TITLE
use list.js

### ISSUE THREAD

**Issue by curtisblackwell** [curtisblackwell/catan_almanac#4]
http://listjs.com/

**Comment by rready** [comment]
I'm using list.js with asp.net mvc, I have a search input on the layout page sidebar with the class='fuzzy-search' it will not work, if I put it in the content page it will work, We are needing this to work on the sidebar layout partial. Is there a reason why it does not pickup the class when it's on the layout page but it does on the content page?

**Comment by curtisblackwell** [comment]
@rready I think you've accidentally posted this in the wrong spot. This isn't the [list.js repo](https://github.com/javve/list.js).
